- hosts: all

    tasks:
    - name: update apt cache
      apt: update_cache=yes cache_valid_time=3600

    roles:
    - toast38coza.djangoapp

    vars:
        postgresql_databases:
            - name: emailservice

        postgresql_users:
            - name: emailservice
            pass: emailservice

        encrypted: no # denotes if the password is already encrypted.
        postgresql_user_privileges:
            - name: emailservice # user name
            db: emailservice # database
            priv: "ALL"

        django_apps:
        - {
            "djangoapp_projectname" : "emailservice",
            "djangoapp_track_branch": "master",
            "djangoapp_repo" : "git@github.com:TangentMicroServices/EmailService.git",
            "path_to_requirements" : "",
            "path_to_managepy" : "",
            "djangoapp_httpport": 8004,
            "djangoapp_static" : true,
            "djangoapp_domains" : "staging.emailservice.tangentme.com",
            "djangoapp_pythonversion" : "2.7",
            "djangoapp_db_engine" : "postgresql_psycopg2",
            "djangoapp_db_host" : "127.0.0.1"
        }
